# typed: false
# frozen_string_literal: true

# This file is generated by apps/cli/scripts/render-formula.ts in
# slingshot/bolter and overwritten on every release. Edits here are lost.
class Sendfm < Formula
  desc "Send and receive end-to-end encrypted files from the command-line"
  homepage "https://send.fm"
  license "MPL-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/slingshot/bolter/releases/download/v0.1.0/sendfm-0.1.0-darwin-arm64.tar.gz"
      sha256 "678531d3e137ec925044b9ff5575554a245dfccf96fbac43f3173462f2bce90d"
    end
    on_intel do
      url "https://github.com/slingshot/bolter/releases/download/v0.1.0/sendfm-0.1.0-darwin-x64.tar.gz"
      sha256 "9b624ad30a10ccf63c07c25de6ba1ad5a2f707caa1116c1543969abfa2f4fbf3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/slingshot/bolter/releases/download/v0.1.0/sendfm-0.1.0-linux-arm64.tar.gz"
      sha256 "7d9b4fdbd1845d0656b18312c4110952a811430da4a82509df474113b9fc60da"
    end
    on_intel do
      url "https://github.com/slingshot/bolter/releases/download/v0.1.0/sendfm-0.1.0-linux-x64.tar.gz"
      sha256 "0f12c2273e42f39d9eac9cb41ea49631de76f463c9eda59387a5248724bad4bd"
    end
  end

  def install
    bin.install "sendfm"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sendfm --version")
  end
end
